export const Dimens = {
	PADDING_XSMALL: 2,
	PADDING_SMALL: 4,
	PADDING_MEDIUM: 8,
	PADDING_REGULAR: 12,
	PADDING_LARGE: 14,
	PADDING_XLARGE: 16,
	MARGIN_XSMALL: 2,
	MARGIN_SMALL: 4,
	MARGIN_MEDIUM: 8,
	MARGIN_REGULAR: 12,
	MARGIN_LARGE: 14,
	MARGIN_XLARGE: 16,
	FONT_SMALL: 12,
	FONT_MEDIUM: 14,
	FONT_REGULAR: 16,
	FONT_LARGE: 18
}

Object.freeze(Dimens)